# Generated by Django 5.2.7 on 2025-10-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
