# Generated by Django 5.2.7 on 2025-10-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default=0, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
